spring.application.name=qma-user-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/qma-auth
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.key=vghjgyufx3456786e$#%^#ERDTFGtghbvh
spring.application.token.expiry=36000
spring.security.oauth2.client.registration.google.client-id={client-id}
spring.security.oauth2.client.registration.google.client-secret={client-secret}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/auth/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true