spring.application.name=API-GATEWAY
spring.application.key=vghjgyufx3456786e$#%^#ERDTFGtghbvh
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://QMA-USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# CORE SERVICE
spring.cloud.gateway.routes[1].id=core-service
spring.cloud.gateway.routes[1].uri=lb://QMA-MEASUREMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/quantities/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# HISTORY SERVICE
spring.cloud.gateway.routes[2].id=history-service
spring.cloud.gateway.routes[2].uri=lb://QMA-HISTORY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/history/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
